version: '3.8'
services:
  db-thesis:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postrges
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin-thesis:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db-thesis
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./mqtt:/mosquitto/config
    ports:
      - 1883:1883
  backend-thesis:
    image: backend-thesis
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8005:8005
    depends_on:
      - mqtt-broker
      - db-thesis
  frontend-thesis:
    image: frontend-thesis
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw