version: '3.8'
services:
  db-thesis:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postrges
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin-thesis:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./mqtt:/mosquitto/config
    ports:
      - 1883:1883